name = "Blog Theme"
license = "MIT"
licenselink = "https://github.com/dominiwe/hugo-dw-blog/blob/master/LICENSE"
description = "Minimal Hugo theme"
homepage = "https://github.com/dominiwe/hugo-dw-blog/"
tags = ["blog", "minimal", "simple", "clean", "gallery"]
features = ["blog", "gallery"]
min_version = "0.66"

[author]
  name = "dominiwe"
  homepage = "https://github.com/dominiwe"
